// generated by tabler
package models

// User

func (u User) CreateTable() string {
    return `CREATE TABLE user (id uuid, created timestamp) PRIMARY KEY (id);`
}

func (u User) DropTable() string {
    return `DROP TABLE user;`
}

func (u User) InsertRow() string {
    return `INSERT INTO user (id, created) VALUES (?, ?);`
}

func (u User) SelectRow() string {
    return `SELECT id, created FROM user WHERE id=?;`
}

// Profile

func (p Profile) CreateTable() string {
    return `CREATE TABLE profile (userid uuid REFERENCES user(id)) PRIMARY KEY (userid);`
}

func (p Profile) DropTable() string {
    return `DROP TABLE profile;`
}

func (p Profile) InsertRow() string {
    return `INSERT INTO profile (userid) VALUES (?);`
}

func (p Profile) SelectRow() string {
    return `SELECT userid FROM profile WHERE userid=?;`
}
